// <auto-generated />
namespace PROG6_Assessment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class KortingToevoegen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KortingToevoegen));
        
        string IMigrationMetadata.Id
        {
            get { return "201501110051448_KortingToevoegen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
